server:
  port : 7001
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        jenkins-processed-data:
          destination: jenkins-processed-data
          contentType: application/json
        bitbucket-processed-data:
          destination: bitbucket-processed-data
          contentType: application/json