server:
  port : 7002
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        jenkins-processed-data:
          destination: jenkins-processed-data
          contentType: application/json

  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: test