server:
  port: 7001
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        jenkins-raw-data:
          destination: jenkins-raw-data
          contentType: application/json
        jenkins-processed-data:
          destination: jenkins-processed-data
          contentType: application/json