server:
  port : 7000
spring:
  batch:
    job:
      enabled: false
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        message-out:
          destination: processorbus
          contentType: application/json