server:
  port : 7001
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        message-in:
          destination: processorbus
          contentType: application/json
        message-out:
          destination: eventBus
          contentType: application/json