server:
  port: 7002
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        jenkins-processed-data:
          destination: jenkins-processed-data
          contentType: application/json
        sonar-processed-data:
          destination: sonar-processed-data
          contentType: application/json